intro1 = 'Some time later...'
intro2 = 'You awaken in a hospital bed. There are no other patients or staff around.'
intro3 = 'Weak and disoriented, you manage to leave the building but still there are no signs of life.'
intro4 = 'The area outside the hospital is in disarray. You stumble around, without sense of direction.'
intro5 = 'Suddenly, a civil defense siren blasts and you seek cover in an abandoned homeware store.'
intro6 = 'From inside, you watch the sky light up in a brief, sharp flash and the siren stops immediately.'
intro7 = 'The sky has turned dark.'
intro8 = 'You notice someone shambling around just outside and you call for help.'
intro9 = 'What turns to face your cries is not human.'
intro10 = 'It lunges towards you and violently attacks.'
intro11 = 'In self-defense, you grab a nearby rolling pin from the floor and bludgeon the creature to death.'
intro12 = 'Startled, you drop the makeshift weapon, ' \
          'staring breathlessly at the creature and at its blood on your hands.'
intro13 = 'The siren starts once more.'
intro14 = 'Another brief flash in the sky, and the creature disappears.'
intro15 = 'You leave the store, in search of safer surroundings...'
